### ISSUE TITLE
Some errors in index.js - Corrected

### ISSUE THREAD

**Issue by BlueBird67** [boades/spo-auth#1]
Hello, I used your code to connect in NODEJS on SharePoint2013 online with great success.

I detected some errors in JS parsing, and added some error detections.

Maybe you would you like me to upload the new file? I have no right on the repo atm.

Thanks for your work.

**Comment by boades** [comment]
Hi! You can create a pull request and I'll check & merge it ASAP. There are lots of tutorials online on how to do it.

**Comment by boades** [comment]
Published a new version to NPM, now it is 1.0.7. 

Thanks!
